# Generated by Django 6.0.6 on 2026-07-12 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Azienda di appartenenza (only for Worker and Manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Work', to='main.business'),
        ),
    ]
